pr:
  branches:
    include:
      - dev

trigger:
 branches:
   include:
     - master


parameters:
- name: runCompletePipeline
  displayName: Run All Tasks ?
  type: boolean
  default: true

stages:
- stage: Build_Stage
  displayName: Build Apps
  jobs:

  - job: WebApp
    displayName: Build Web App
    variables:
      BuildConfiguration: release
    steps:

    - task: UseDotNet@2
      displayName: Install .NET 6 sdk
      inputs:
        packageType: sdk
        version: 6.0.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
