
trigger: 'none' # will disable CI builds entirely
# - master
pr: none
# - master
# - releases/*
pool:
  name: WindowsAgent

parameters:
- name: runCompletePipeline
  displayName: Run All Tasks ?
  type: boolean
  default: true

stages:
- stage: Build_Stage
  displayName: Build Apps
#pool:
#  vmImage: 'windows-latest'

  jobs:
  - job: WebApp
    displayName: 'Build Web App'
    pool:
      vmImage: 'windows-latest'
    variables:
      BuildConfiguration: release
    
    steps:
    
    - task: UseDotNet@2
      displayName: Install .NET 6 sdk
      inputs:
        packageType: sdk
        version: 6.0.x
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: DotNetCoreCLI@2
      displayName: Restore Nuget Packages
      inputs:
        command: restore
        projects: '**/WebApp.csproj'

    - task: DotNetCoreCLI@2
      displayName: Build WebApp
      inputs:
        projects: '**/WebApp.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Run Unit Tests
      enabled: ${{ parameters.runCompletePipeline }}
      inputs:
        command: test
        projects: '**/*UnitTest*.csproj'
        arguments: '--configuration $(BuildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Create WebApp.zip
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True

    - task: PublishBuildArtifacts@1
      displayName: Publish Artifact (WebApp.zip)
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: drop
